services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "8080:3000"
    user : '0'
    volumes:
      - './data/grafana:/var/lib/grafana'
    networks:
      - monitoring
    depends_on:
      - prometheus
      - alertmanager
      - loki
      - promtail
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command: -config.file="/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - "./config/:/etc/prometheus/"
      - "./data/prometheus:/prometheus"
    networks:
      - monitoring
    restart: always
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    command: -config.file="/etc/alertmanager/alertmanager.yml"
    ports:
      - "9093:9093"
    volumes:
      - "./config/:/etc/alertmanager/"
      - "./data/alertmanager:/alertmanager"
    networks:
      - monitoring
    restart: always
  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file="/etc/loki/loki.yml"
    ports:
      - 3100:3100
      - 7946
      - 9095
    volumes:
      - "./config:/etc/loki/"
      - "./data/loki:/loki"
    networks:
      - monitoring
    restart: always
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    user: "102"
    command: -config.file="/etc/promtail/promtail.yml"
    volumes:
    
      - "/var/log:/var/logs:ro,z"
      - "./config:/etc/promtail/"
    networks:
      - monitoring
    restart: always
networks:
  monitoring:
    driver: bridge